#========================================
# Test profile settings (junit tests)
#========================================
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///test-junit
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
            create-source: metadata
      hibernate:
        ddl-auto: validate
        hbm2ddl:
          charset_name: 'UTF-8'
          schema-generation:
            script:
              append: 'false'
        format_sql: 'true'
  security:
    oauth2:
      client:
        provider:
          employee:
            token-uri: junit-token-url
        registration:
          employee:
            client-id: junit-client-id
            client-secret: junit-client-secret
integration:
  employee:
    url: junit-employe-url
    connect-timeout: 3
    read-timeout: 4
