#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-messaging-settings
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          employee:
            authorization-grant-type: client_credentials
            provider: employee
integration:
  employee:
    connect-timeout: 2
    read-timeout: 10
