#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///test-junit
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
            create-source: metadata
      hibernate:
        ddl-auto: validate
        hbm2ddl:
          charset_name: 'UTF-8'
          schema-generation:
            script:
              append: 'false'
        format_sql: 'true'
